GET http://localhost:3000/car

POST http://localhost:3000/car
Content-Type: application/json

{
    "name":"VF10",
    "pictureURL": "https://cmu-cdn.vinfast.vn/2023/01/3468b46e-3.jpg"
}

GET http://localhost:3000/carVer

POST http://localhost:3000/carVer
Content-Type: application/json

{
"isBaterry": false,
"verName": "VF9 Eco Green",
"__v": 0,
"carID": "67108238415848a6b5e6faa9",
"price": 1589,
"acceleration": 7.3,
"battery": 92,
"dist": 423,
"height": 1696,
"length": 5119,
"maxPower": 300,
"seatsNumber": 7,
"weight": 2830,
"width": 2004
}

GET http://localhost:3000/rate

POST http://localhost:3000/rate
Content-Type: application/json

{
    "BankName": "LBB",
    "MaxPercent": 100,
    "MaxTerm": 8,
    "Rate": 7.9
}


### Request to test login API
POST http://localhost:3000/admin
Content-Type: application/json

{
  "username": "QTrang",
  "password": "QTrang123"
}
