name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.199.134.219 >> ~/.ssh/known_hosts
    - name: Deploy to EC2
      run: |
          ssh -i ~/.ssh/id_rsa ubuntu@34.199.134.219 "
            cd BTL_PTPMHDV_N6 || { echo 'Failed to change directory'; exit 1; } &&
            git pull origin main || { echo 'Failed to pull from git'; exit 1; } &&
            cd backend || { echo 'Failed to change to backend directory'; exit 1; } &&
            npm install || { echo 'npm install failed'; exit 1; } &&
            pm2 restart index.js || { echo 'Failed to restart pm2'; exit 1; }
          "

     
