name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploys
      env: 
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST_NAME: ${{secrets.EC2_HOST}}
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /BTL_PTPMHDV_N6 &&
              git pull origin main
              cd backend
              pm2 restart index.js
              '

     
