name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploys
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.199.134.219 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-34.199.134.219.compute-1.amazonaws.com
          # Now we have got the access of EC2 and we will start the deploy .
          cd /BTL_PTPMHDV_N6 &&
          git pull origin main
          cd backend
          npm install 
          pm2 restart index.js
          '

     
