name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
    - name: Run commands on EC2
      run: |
        ssh "${{ secrets.EC2_HOST }}" "cd /BTL_PTPMHDV_N6 && git pull origin main && npm install && pm2 restart index.js && echo 'Update successfully'"

     
